project:
  type: website

website:
  title: "Augmented tuto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: appendices.qmd
        text: Appendices

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <meta name="robots" content="noindex, nofollow">
